version: "3.9"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    environment:
      - TZ=Asia/Tokyo

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic:/etc/traefik/dynamic:ro
      - ./traefik/acme:/etc/traefik/acme
      - ./certs:/certs:ro

    networks:
      - service_network

networks:
  service_network:
    external: true
